version: '3.8'

services:
  db:
    image: postgres:14
    container_name: afm_postgres
    environment:
      POSTGRES_USER: afm_user
      POSTGRES_PASSWORD: afm_password
      POSTGRES_DB: AFM
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
