--schema.sql--
-- Create the AFM database if it doesn't already exist
DO
$do$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_database WHERE datname = 'AFM') THEN
      PERFORM dblink_exec('dbname=postgres', 'CREATE DATABASE AFM');
   END IF;
END
$do$;

-- Switch to the AFM database
\c AFM;
-- -- THIS IS THE CLEANUP plz keep me here
-- DO $$ DECLARE
--     r RECORD;
-- BEGIN
--     FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
--         EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
--     END LOOP;
-- END $$;


-- Table for Water Levels --> created based on the possible attributes that can be found in the second link
DROP TABLE IF EXISTS Water_Levels;

-- Create a simple Water_Levels table for testing
CREATE TABLE Water_Levels (
    id SERIAL PRIMARY KEY,  -- Primary key expected by Django
    location_id INTEGER,
    value_at_time NUMERIC(10, 2),
    unit VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS FloodReport;

-- Create the FloodReport table to store flood report information
CREATE TABLE FloodReport (
    ID SERIAL PRIMARY KEY, -- Unique identifier for each report
    Location TEXT NOT NULL, -- Location of the flood (to be generated by the backend for now)
    AssociatedEmail VARCHAR(255) NOT NULL, -- Email of the person submitting the report (mandatory)
    AssociatedPhoneNumber VARCHAR(15), -- Optional phone number of the submitter
    AssociatedUserID INT, -- Optional user ID for registered users (can be NULL for anonymous reports)
    Description TEXT, -- Optional description of the flood situation
    LinkToPicture TEXT, -- Optional link to an uploaded picture of the flood
    Severity VARCHAR(50) NOT NULL CHECK (Severity IN ('low', 'medium', 'high', 'catastrophical')), -- Severity of the flood (mandatory)
    Verified INTEGER NOT NULL DEFAULT 0 CHECK (Verified IN (0, 1, 2)) -- 0: Unverified, 1: Verified, 2: Rejected
);

CREATE TABLE EmergencyResponse (
    ID SERIAL PRIMARY KEY,
    Status VARCHAR(50) NOT NULL DEFAULT 'Planning', -- Default status is "Planning"
    ReportID INT NOT NULL REFERENCES FloodReport(ID) ON DELETE CASCADE -- Foreign key to link reports
);



-- Table for Locations
-- CREATE TABLE IF NOT EXISTS Locations (
--     location_id SERIAL PRIMARY KEY,
--     dbmsnr INTEGER UNIQUE, -- Internal database number
--     hzbnr INTEGER UNIQUE, -- Measuring point number of the hydrographic service
--     water_body_name VARCHAR(255), -- water body name
--     mp_operator VARCHAR(255), -- Operator of the measuring point
--     lat NUMERIC(2, 6), -- up to 9 digits and up to 6 decimal places --> Y coordinates
--     lon NUMERIC(3, 6), -- X coordinates
--     internet TEXT, -- Direct link to the measuring point on the operator's website
--     country TEXT DEFAULT "Austria", -- Country information for measuring points outside Austria
--     -- Do we even need the "country" attribute??
--     mp_geometry GEOMETRY(Polygon, 4326), -- mp stands for measuring point (MAYBE NEED TO USE: mp_geometry POLYGON)
--     -- Geometry as Polygon, using SRID 4326 for WGS84
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );



-- CREATE TABLE IF NOT EXISTS Water_Level_History (
--     entry_id SERIAL PRIMARY KEY,
--     location_id INTEGER REFERENCES Locations(location_id) ON DELETE CASCADE,  -- Links to location if applicable
--     category_label VARCHAR(255),           -- Category label (e.g., CRS or projection system)
--     category_term TEXT,                    -- Category term (e.g., EPSG code)
--     title TEXT,                            -- Title of the dataset
--     summary TEXT,                          -- Summary of dataset description (german...)
--     last_updated TIMESTAMP,                -- Timestamp of last dataset update
--     geom GEOMETRY(POLYGON, 4326),          -- Polygon coordinates (stored as GEOMETRY type for spatial use)
--     hq30 GEOMETRY(POLYGON, 4326),          -- HQ30 (30-year flood value), as an example value
--     all_time_high NUMERIC(10, 2),          -- All-time high water level
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );


-- Table for Water Levels
CREATE TABLE IF NOT EXISTS Users (
    user_id SERIAL PRIMARY KEY,                     -- Unique identifier for each user
    email VARCHAR(255) UNIQUE NOT NULL,             -- Email address, unique and required
    hashed_passw VARCHAR(255) NOT NULL,             -- Hashed password (255 to accommodate long hashes)
    phone_num VARCHAR(15),                          -- Phone number (optional, allows for country codes)
    user_address TEXT,                              -- User's address (text for flexibility in length, can use VARCHAR(255) if needed)
    perm_level int DEFAULT 1 CHECK (perm_level IN (0,1,2,3,4)),        -- Permission level (right now it can be user or admin)
    -- 0: Guest; 1: User; 2: Moderator; 3: Emergency Service; 4: Admin
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      -- Timestamp of user creation --> may be used for statistics (if not, it can be easily deleted)
    last_rejected_on TIMESTAMP,
    ESRejected BOOLEAN DEFAULT FALSE
);



-- Create PromotionRequests table if it doesn't exist
CREATE TABLE IF NOT EXISTS PromotionRequests (
    request_id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES Users(user_id),
    requested_role INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    rejected_on TIMESTAMP,
    type VARCHAR(20) CHECK (type IN ('Moderator', 'Emergency Service'))
);


-- Insert a default admin user
Insert into Users (email, hashed_passw, perm_level) 
values ('admin@example.com', 'pbkdf2:sha256:1000000$p05Dwd3ap9ogMdkI$7f4e1fcba3da1beec50f690cc57047c4ee81afde904dadb0632a534ed555e3d2', 4);

-- First set of users (a@a.com pattern)
INSERT INTO Users (email, hashed_passw, perm_level) VALUES
('a@a.com', 'pbkdf2:sha256:1000000$vK9jF8nM$e7c22b37d13be86f12a719188e4817441fd6eb7748a81869b6c012959d51da54', 1),
('b@a.com', 'pbkdf2:sha256:1000000$pL8kR2xN$f9d33b48c5e21a94f7d8e9b752e6d890a3c12e45b6f89d237c901b436e982f1c', 1),
('c@a.com', 'pbkdf2:sha256:1000000$mQ7tH4wP$a1b52c63d84e95f607h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9', 1),
('d@a.com', 'pbkdf2:sha256:1000000$nS6yJ3vL$b2c63d74e85f96g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0', 1),
('e@a.com', 'pbkdf2:sha256:1000000$kT5xM2bN$c3d74e85f96g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1', 1);


INSERT INTO Users (email, hashed_passw, perm_level) VALUES
('a@gov.com', 'pbkdf2:sha256:1000000$rU9zG4hK$d4e85f96g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2', 1),
('b@gov.com', 'pbkdf2:sha256:1000000$qV8wH5jM$e5f96g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3', 1),
('c@gov.com', 'pbkdf2:sha256:1000000$pW7vJ6kN$f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4', 1),
('d@gov.com', 'pbkdf2:sha256:1000000$oX6uK7mP$g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5', 1),
('e@gov.com', 'pbkdf2:sha256:1000000$nY5tL8nQ$h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6', 1);


INSERT INTO PromotionRequests (user_id, requested_role, type)
SELECT user_id, 2, 'Moderator'
FROM Users 
WHERE email LIKE '%@a.com';


INSERT INTO PromotionRequests (user_id, requested_role, type)
SELECT user_id, 3, 'Emergency Service'
FROM Users 
WHERE email LIKE '%@gov.com';


-- For a@a.com
INSERT INTO FloodReport (Location, AssociatedEmail, Description, Severity, Verified)
VALUES 
    ('47.557433,13.761592', 'a@a.com', 'Flooding near lake shore', 'low', 0),
    ('47.558123,13.762001', 'a@a.com', 'Water level rising rapidly', 'medium', 0),
    ('47.556891,13.761123', 'a@a.com', 'Street partially submerged', 'high', 0),
    ('47.557012,13.760897', 'a@a.com', 'Basement flooding reported', 'medium', 0),
    ('47.557789,13.761234', 'a@a.com', 'Minor flooding in parking area', 'low', 0);

-- For b@a.com
INSERT INTO FloodReport (Location, AssociatedEmail, Description, Severity, Verified)
VALUES 
    ('47.557901,13.761782', 'b@a.com', 'Water accumulating in town square', 'medium', 0),
    ('47.558234,13.761123', 'b@a.com', 'Flood warning needed', 'high', 0),
    ('47.557345,13.760987', 'b@a.com', 'Rising water levels observed', 'medium', 0),
    ('47.557567,13.761432', 'b@a.com', 'Road becoming impassable', 'high', 0),
    ('47.557890,13.761654', 'b@a.com', 'Minor flooding near shops', 'low', 0);

-- Similar pattern for other users with varying coordinates and descriptions
-- For a@gov.com
INSERT INTO FloodReport (Location, AssociatedEmail, Description, Severity, Verified)
VALUES 
    ('47.557433,13.761592', 'a@gov.com', 'Emergency response needed', 'high', 0),
    ('47.558123,13.762001', 'a@gov.com', 'Critical flooding situation', 'catastrophical', 0),
    ('47.556891,13.761123', 'a@gov.com', 'Immediate evacuation required', 'high', 0),
    ('47.557012,13.760897', 'a@gov.com', 'Infrastructure damage reported', 'high', 0),
    ('47.557789,13.761234', 'a@gov.com', 'Multiple buildings affected', 'catastrophical', 0);

-- Continuing for other emails...
-- Adding just a few more examples (we can add the rest if needed)
INSERT INTO FloodReport (Location, AssociatedEmail, Description, Severity, Verified)
VALUES 
    ('47.557433,13.761592', 'b@gov.com', 'Emergency assessment required', 'high', 0),
    ('47.558123,13.762001', 'c@gov.com', 'Critical situation developing', 'catastrophical', 0),
    ('47.556891,13.761123', 'd@gov.com', 'Urgent response needed', 'high', 0),
    ('47.557012,13.760897', 'e@gov.com', 'Major flooding event', 'high', 0),
    ('47.557789,13.761234', 'c@a.com', 'Flood warning issued', 'medium', 0);

-- Log a message to indicate that the schema.sql file has finished executing
\echo 'Finished executing schema.sql'